"""
Migration 0001 – Initial Schema
================================

Auto-generated by Django 6.0.4 on 2026-05-03 09:14.

This is the **first and only** migration for the ``core`` application.  It
creates the complete initial database schema for all three domain models in a
single atomic operation.

Tables Created
--------------
``core_user``
    Stores the single application user (PIN-auth model).

    +--------------------+------------------+----------------------------------+
    | Column             | Type             | Notes                            |
    +====================+==================+==================================+
    | userID             | AutoField (PK)   | Auto-incrementing primary key    |
    +--------------------+------------------+----------------------------------+
    | userName           | VARCHAR(64)      | Display name                     |
    +--------------------+------------------+----------------------------------+
    | hashedPIN          | VARCHAR(256)     | SHA-256 hex digest of the PIN    |
    +--------------------+------------------+----------------------------------+
    | preferredCurrency  | VARCHAR(10)      | Defaults to ``'EGP'``            |
    +--------------------+------------------+----------------------------------+

``core_budgetcycle``
    Represents one budget period linked to a user.

    +----------------+------------------+--------------------------------------+
    | Column         | Type             | Notes                                |
    +================+==================+======================================+
    | cycleID        | AutoField (PK)   | Auto-incrementing primary key        |
    +----------------+------------------+--------------------------------------+
    | user_id        | FK → core_user   | CASCADE on delete                    |
    +----------------+------------------+--------------------------------------+
    | totalAllowance | FLOAT            | Total budget for the cycle           |
    +----------------+------------------+--------------------------------------+
    | dailyLimit     | FLOAT            | Pre-computed at cycle creation       |
    +----------------+------------------+--------------------------------------+
    | startDate      | DATE             | Cycle start (today at creation time) |
    +----------------+------------------+--------------------------------------+
    | endDate        | DATE             | Cycle end (chosen by the user)       |
    +----------------+------------------+--------------------------------------+

``core_transaction``
    Individual expense or income entries linked to a budget cycle.

    +------------------+----------------------+--------------------------------+
    | Column           | Type                 | Notes                          |
    +==================+======================+================================+
    | id               | BigAutoField (PK)    | Auto-incrementing primary key  |
    +------------------+----------------------+--------------------------------+
    | budget_cycle_id  | FK → budgetcycle     | CASCADE; related_name='transactions' |
    +------------------+----------------------+--------------------------------+
    | title            | VARCHAR(255)         | Short label for the expense    |
    +------------------+----------------------+--------------------------------+
    | amount           | DECIMAL(10, 2)       | Monetary value                 |
    +------------------+----------------------+--------------------------------+
    | transaction_type | VARCHAR(10)          | ``'expense'`` or ``'income'``; default ``'expense'`` |
    +------------------+----------------------+--------------------------------+
    | category         | VARCHAR(100)         | Optional; nullable             |
    +------------------+----------------------+--------------------------------+
    | date             | DATE                 | Date of the transaction        |
    +------------------+----------------------+--------------------------------+
    | description      | TEXT                 | Optional note; nullable        |
    +------------------+----------------------+--------------------------------+
    | created_at       | DATETIME             | Auto-set on insert             |
    +------------------+----------------------+--------------------------------+

    Default ordering: ``['-date', '-created_at']`` (most recent first).

Operation Order
---------------
1. Create ``BudgetCycle`` (without its user FK — added in step 4).
2. Create ``User``.
3. Create ``Transaction`` (with FK to ``BudgetCycle``).
4. Add FK ``BudgetCycle.user`` → ``User`` (via ``AddField``).

   This order avoids a forward-reference problem: Django creates ``BudgetCycle``
   first, then retroactively adds the ``user`` foreign key once ``User`` exists.

References
----------
Django migrations documentation:
    https://docs.djangoproject.com/en/6.0/topics/migrations/
"""

# Generated by Django 6.0.4 on 2026-05-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration: creates the full core application schema from scratch.

    Attributes
    ----------
    initial : bool
        Marks this as the first migration in the dependency chain.
        Django uses this flag to determine that no prior migration needs
        to run before this one.
    dependencies : list
        Empty — no other apps need to be migrated first.
    operations : list of MigrationOperation
        Four operations executed in sequence within a single database
        transaction (atomic by default).
    """

    initial = True

    dependencies = []

    operations = [

        # ------------------------------------------------------------------
        # 1. Create the BudgetCycle table (user FK added later in step 4)
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='BudgetCycle',
            fields=[
                # Auto-incrementing integer primary key
                ('cycleID',        models.AutoField(primary_key=True, serialize=False)),
                ('totalAllowance', models.FloatField()),
                ('dailyLimit',     models.FloatField()),
                ('startDate',      models.DateField()),
                ('endDate',        models.DateField()),
            ],
        ),

        # ------------------------------------------------------------------
        # 2. Create the User table
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='User',
            fields=[
                # Auto-incrementing integer primary key
                ('userID',            models.AutoField(primary_key=True, serialize=False)),
                ('userName',          models.CharField(max_length=64)),
                # Stores the SHA-256 hex digest of the user's PIN
                ('hashedPIN',         models.CharField(max_length=256)),
                # Currency code used across the UI; defaults to Egyptian Pound
                ('preferredCurrency', models.CharField(default='EGP', max_length=10)),
            ],
        ),

        # ------------------------------------------------------------------
        # 3. Create the Transaction table (references BudgetCycle created above)
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='Transaction',
            fields=[
                # Auto-incrementing big-integer primary key (Django default)
                ('id',               models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('title',            models.CharField(max_length=255)),
                ('amount',           models.DecimalField(decimal_places=2, max_digits=10)),
                # Restricted to 'expense' or 'income'; defaults to 'expense'
                ('transaction_type', models.CharField(
                    choices=[('expense', 'Expense'), ('income', 'Income')],
                    default='expense', max_length=10
                )),
                # Optional free-text category entered by the user
                ('category',         models.CharField(blank=True, max_length=100, null=True)),
                ('date',             models.DateField()),
                # Optional longer description or note
                ('description',      models.TextField(blank=True, null=True)),
                # Automatically set to the current timestamp on INSERT
                ('created_at',       models.DateTimeField(auto_now_add=True)),
                # FK to BudgetCycle: deleting a cycle cascades to its transactions
                ('budget_cycle',     models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='transactions',
                    to='core.budgetcycle',
                )),
            ],
            options={
                # Default queryset ordering: newest transaction first
                'ordering': ['-date', '-created_at'],
            },
        ),

        # ------------------------------------------------------------------
        # 4. Add the user FK to BudgetCycle (deferred to avoid forward reference)
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='budgetcycle',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.user',
                # Deleting a user cascades to all their budget cycles,
                # which in turn cascades to all transactions (via step 3).
            ),
        ),
    ]
