# Generated by Django 6.0.4 on 2026-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=64)),
                ('hashedPIN', models.CharField(max_length=256)),
                ('preferredCurrency', models.CharField(default='EGP', max_length=10)),
            ],
        ),
    ]
