"""
core.migrations
===============

Package containing all Django database migrations for the **core**
application.

Django's migration framework uses the files in this directory to track and
apply incremental changes to the database schema.  Each migration file is
auto-generated by ``manage.py makemigrations`` and should **not** be edited
manually unless you know exactly what you are doing.

Migrations
----------
0001_initial
    Creates the initial schema for all three core models (``User``,
    ``BudgetCycle``, ``Transaction``) and establishes the foreign-key
    relationships between them.

Running migrations
------------------
Apply all pending migrations to the database:

.. code-block:: bash

    python manage.py migrate

Inspect the current migration state:

.. code-block:: bash

    python manage.py showmigrations core

Generate a new migration after editing a model:

.. code-block:: bash

    python manage.py makemigrations core

References
----------
Django migrations documentation:
    https://docs.djangoproject.com/en/6.0/topics/migrations/
"""
