"""
Django Settings – masroofy
============================

Central configuration module for the **masroofy** project, generated by
``django-admin startproject`` and customised for local development.

Sections
--------
* Paths          – base directory resolution
* Security       – secret key, debug flag, allowed hosts
* Applications   – installed Django apps
* Middleware     – request/response processing pipeline
* Templates      – template engine configuration
* Database       – SQLite backend pointing at ``database/masroofy.db``
* Auth           – password-validation rules
* Internationalisation – language, timezone, i18n switches
* Static files   – URL prefix for CSS/JS/images

.. warning::
    Several settings below are **development-only** and **must** be changed
    before deploying to production.  See Django's deployment checklist:
    https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

References
----------
Full settings reference:
    https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

#: Absolute path to the repository root (two levels above this file).
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

# .. warning::
#     Replace this key with a long random value before going to production,
#     and load it from an environment variable or secrets manager — never
#     commit a real secret key to version control.
SECRET_KEY = 'django-insecure-4axjl*h9pmu73tgvngclqqt=to!*a20d45-p__s%#7nqp6swnj'

# .. warning::
#     Set ``DEBUG = False`` in production. With DEBUG enabled, Django renders
#     detailed error pages that may expose sensitive configuration details.
DEBUG = True

#: List of host/domain names that Django will serve.
#: Must be populated in production (e.g. ``['masroofy.example.com']``).
ALLOWED_HOSTS = []


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

#: All Django applications active in this project.
#: ``core.apps.CoreConfig`` is the main business-logic app.
INSTALLED_APPS = [
    'django.contrib.admin',        # Admin site
    'django.contrib.auth',         # Authentication framework
    'django.contrib.contenttypes', # Generic relations support
    'django.contrib.sessions',     # Server-side session framework
    'django.contrib.messages',     # Flash-message framework
    'django.contrib.staticfiles',  # Static-file serving helper
    'core.apps.CoreConfig',        # Masroofy core app (expenses, users, reports)
]


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

#: Ordered list of middleware classes applied to every request/response cycle.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # HTTPS/HSTS enforcement
    'django.contrib.sessions.middleware.SessionMiddleware',    # Session cookie handling
    'django.middleware.common.CommonMiddleware',               # URL normalisation (trailing slash etc.)
    'django.middleware.csrf.CsrfViewMiddleware',               # CSRF token validation
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Attaches ``request.user``
    'django.contrib.messages.middleware.MessageMiddleware',    # Flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # X-Frame-Options header
]

#: Dotted path to the root URL configuration module.
ROOT_URLCONF = 'masroofy.urls'


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

TEMPLATES = [
    {
        # Use Django's built-in template engine.
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Template directories outside of apps.
        # Uncomment and set the path when project-level templates are needed:
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 'DIRS': [os.path.join.(BASE_DIR, 'templates')],  # NOTE: typo (dot before join) – fix before use

        # Automatically discover templates inside each app's ``templates/`` folder.
        'APP_DIRS': True,

        'OPTIONS': {
            # Built-in context processors available to every template.
            'context_processors': [
                'django.template.context_processors.request',  # Adds ``request`` to context
                'django.contrib.auth.context_processors.auth', # Adds ``user`` and ``perms``
                'django.contrib.messages.context_processors.messages', # Flash messages
            ],
        },
    },
]

#: Dotted path to the WSGI application used by Django's built-in server.
WSGI_APPLICATION = 'masroofy.wsgi.application'


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#: Database connection settings.
#: Uses SQLite stored at ``<BASE_DIR>/database/masroofy.db``.
#: For production, switch to PostgreSQL or another production-grade backend.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'database' / 'masroofy.db',
    }
}


# ---------------------------------------------------------------------------
# Password Validation
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

#: Validators that enforce password strength on new/changed passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords too similar to the user's own attributes (name, email …).
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Enforces a minimum character length (default: 8).
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Rejects passwords found in Django's common-password list.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Rejects entirely numeric passwords.
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/topics/i18n/

#: Default language code (BCP 47 format).
LANGUAGE_CODE = 'en-us'

#: Default time zone used for datetime display when ``USE_TZ`` is True.
TIME_ZONE = 'UTC'

#: Enable Django's translation framework.
USE_I18N = True

#: Store datetimes as timezone-aware values in the database.
USE_TZ = True


# ---------------------------------------------------------------------------
# Static Files
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#: Additional directories searched by ``collectstatic`` / the dev server.
#: Each app's own ``static/`` folder is included automatically via ``APP_DIRS``.
STATICFILES_DIRS = []

#: URL prefix under which static files are served.
STATIC_URL = 'static/'
