"""
Views – core (stub)
====================

This file is the default ``views.py`` stub generated by Django.

.. note::
    In this project, views are **not** defined in this file.  Instead they
    are organised into a ``core/views/`` sub-package, with one module per
    functional domain:

    +------------------------------+------------------------------------------+
    | Module                       | Responsibility                           |
    +==============================+==========================================+
    | ``core/views/login_view.py`` | ``login``, ``signup``, ``logout``        |
    +------------------------------+------------------------------------------+
    | ``core/views/home_view.py``  | ``setup``, ``dashboard``                 |
    +------------------------------+------------------------------------------+
    | ``core/views/add_expense_view.py`` | ``add_expense``                  |
    +------------------------------+------------------------------------------+
    | ``core/views/history_view.py`` | ``history``, ``delete_transaction``,   |
    |                              | ``edit_transaction``                     |
    +------------------------------+------------------------------------------+
    | ``core/views/settings_view.py`` | ``settings``, ``reset_cycle``         |
    +------------------------------+------------------------------------------+
    | ``core/views/reports_view.py`` | ``reports``                            |
    +------------------------------+------------------------------------------+

    This file may be removed once the ``core/views/`` package is fully in
    place, or retained as a convenience re-export::

        from core.views.login_view import login, signup, logout
        from core.views.home_view  import setup, dashboard
        # … etc.

References
----------
Django views documentation:
    https://docs.djangoproject.com/en/6.0/topics/http/views/
"""

from django.shortcuts import render

# Create your views here.
